# Generated by Django 5.1.6 on 2025-02-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Finance', 'Finance Professional')], max_length=50),
        ),
    ]
