# Generated by Django 4.2.7 on 2025-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='reportType',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
