# Generated by Django 4.2.7 on 2025-02-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_financialdocument_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
