# Generated by Django 4.2.7 on 2025-02-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_financialdocument_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='organization.financialdocument')),
            ],
            options={
                'verbose_name': 'Balance Sheet Data',
                'verbose_name_plural': 'Balance Sheet Data',
                'ordering': ['-processed_at'],
            },
        ),
    ]
