# Generated by Django 5.1.6 on 2025-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_balancesheetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
