# Generated by Django 5.1.6 on 2025-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_financialdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='file_type',
            field=models.CharField(choices=[('CHARGESHEET', 'Chargesheet'), ('BALANCESHEET', 'Balance Sheet')], default='BALANCESHEET', max_length=20),
        ),
    ]
