# Generated by Django 5.1.6 on 2025-02-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_financialdocument_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocument',
            name='file_type',
        ),
        migrations.CreateModel(
            name='ChargesheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargesheets', to='organization.financialdocument')),
            ],
            options={
                'verbose_name': 'Chargesheet Data',
                'verbose_name_plural': 'Chargesheet Data',
                'ordering': ['-processed_at'],
            },
        ),
    ]
