# Generated by Django 5.1.6 on 2025-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_financialdocument_file_type_chargesheetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='reportType',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BALANCE_SHEET', 'Balance Sheet'), ('CHARGESHEET', 'Charge Sheet')], default='OTHER', max_length=50),
        ),
    ]
