# Generated by Django 5.1.6 on 2025-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_financialdocument_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
    ]
