# Generated by Django 5.1.6 on 2025-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_financialdocument_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdocument',
            old_name='reportType',
            new_name='report_type',
        ),
    ]
