# Generated by Django 5.1.6 on 2025-02-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_organization_and_more'),
        ('organization', '0012_rename_reporttype_financialdocument_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_balance_sheets', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='chargesheetdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_chargesheets', to='authentication.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheetdata',
            unique_together={('organization', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='chargesheetdata',
            unique_together={('organization', 'document', 'date')},
        ),
    ]
