# Generated by Django 5.1.6 on 2025-02-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_balancesheetdata_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancesheetdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chargesheetdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='report_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BALANCE_SHEET', 'Balance Sheet'), ('CHARGESHEET', 'Charge Sheet')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.RemoveField(
            model_name='balancesheetdata',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chargesheetdata',
            name='organization',
        ),
    ]
