# Generated by Django 5.1.6 on 2025-02-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_organization_income_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='income',
            name='organization',
        ),
    ]
